fb_instant_articles_api.settings:
  type: config_object
  mapping:
    app_id:
      type: string
      label: 'App ID'
    app_secret:
      type: string
      label: 'App secret'
    access_token:
      type: string
      label: 'Access token'
    page_access_token:
      type: string
      label: 'Page access token'
